name: you_can_flutter_sdk
description: he YouCan E-commerce platform SDK for Flutter/Dart, built for a better developer experience
version: 1.0.0

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  dart_code_metrics: ^5.3.0
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
